### ISSUE TITLE
Add the first CI model building

### ISSUE THREAD

**Issue by mmikhasenko** [RUB-EP1/amplitude-serialization#24]
`ThreeBodyDecayIO.jl` is ready to be show cased with the 
1) model deserialization,
2) validation, and 
3) plotting

https://github.com/mmikhasenko/ThreeBodyDecaysIO.jl/blob/main/builders/Lc2pKpi_read.jl#L93-L96

Would be cool to add CI routine to run the julia file
I thinking to use https://github.com/fredrikekre/Literate.jl for producing html pages.

**Comment by redeboer** [comment]
I have been investigating what is the best way to do this. The idea:
1. Each language/frameworks provides a jinja template that tells the general procedure to load the model and do stuff with it (validate, plot, etc.).
2. Each template generates a page for each model in this repo (currently only `Lc2ppik.json`).
3. The template is most likely some Markdown flavor with explanatory text around code cells.

The question is which ecosystem to use to generate html pages. Some requirements:
- It supports a mixture of code and explanatory text (à la Pluto, Jupyter notebook, etc.)
- It supports multiple languages (from what I understand, [`Literate.jl`](https://github.com/fredrikekre/Literate.jl) does not tick this box)
- It is easy to write read and write with a normal text editor (like a script). Jupyter notebooks do not fall under this, because you need a special editor to sense of the JSON.

Nowadays there is a whole [landscape of tools that try to do this](https://compwa.github.io/symbolics#self-documenting-workflow).
I gave MyST-NB (i.e. Sphinx ecosystem) a try, with [text-based notebooks](https://myst-nb.readthedocs.io/en/latest/authoring/text-notebooks.html#syntax-for-markdown), but it seems that you need to convert to a jupyter notebook first to generate HTML. Quarto is a good candidate too, but from my first experiences, it is quite invasive (system-wide install, bad access to packages in a virtual environment). From what I understand, Quarto also introduces yet another conversion step in the chain towards HTML:
[![image](https://github.com/RUB-EP1/amplitude-serialization/assets/29308176/79a508c2-716e-4015-965f-1d0bb42994e0)](https://quarto.org/docs/get-started/hello/vscode.html)

At any rate, just an update, trying both Quarto and MyST-NB to further weigh he pros and cons.

**Comment by redeboer** [comment]
As a side note, here's a preview of an HTML build of the model description, but it does not yet include the example scripts.

**Comment by mmikhasenko** [comment]
Wow, It looks nice and clear!

There is an example of julia model reader
https://github.com/mmikhasenko/ThreeBodyDecaysIO.jl/blob/main/builders/Lc2pKpi_read.jl

1) defined missing functions
2) builds workspace with all objects
3) make validation
4) makes plotting: I just noticed that I call `my_model_for_reaction_intensity`, too specific. Instead I can loop over workspace and find `<: ThreeBodyDecay` object and plot it

**Comment by redeboer** [comment]
The Julia kernel error we discussed yesterday is caused by Julia when installed directly from conda-forge (https://anaconda.org/conda-forge/julia). Running some Julia script through Jupyter Lab, MyST-NB, or Quarto always results in:
```
ERROR: LoadError: Could not find MD type for kind MD_SHA256
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] MDInfo
   @ ~/.julia/packages/MbedTLS/Vaaz8/src/md.jl:38 [inlined]
 [3] MbedTLS.MD(kind::MbedTLS.MDKind, key::String)
   @ MbedTLS ~/.julia/packages/MbedTLS/Vaaz8/src/md.jl:82
 [4] init(args::Vector{String})
   @ IJulia ~/.julia/packages/IJulia/Vo51o/src/init.jl:79
 [5] top-level scope
   @ ~/.julia/packages/IJulia/Vo51o/src/kernel.jl:24
in expression starting at ~/.julia/packages/IJulia/Vo51o/src/kernel.jl:24
```
When using a Julia installation from [`juliaup`](https://anaconda.org/conda-forge/julia) the error is gone and Julia code can be run from a text-based notebook. Temporary preview from 5db78e7 here: https://redeboer.github.io/amplitude-serialization/julia/lc2pkpi

![image](https://github.com/RUB-EP1/amplitude-serialization/assets/29308176/1eb8d087-df25-4fea-a327-a62c53c4cb12)

**Comment by mmikhasenko** [comment]
So cool!

**Comment by redeboer** [comment]
There's now a text-based julia notebook with output
https://redeboer.github.io/amplitude-serialization/julia/lc2pkpi

Decided to switch from Sphinx to Quarto after all, got it to work nicely through pixi.

**Comment by redeboer** [comment]
@IlyaSegal
